# https://docs.haskellstack.org/en/stable/travis_ci/

sudo: true
dist: bionic
language: generic
addons:
  apt:
    update: true
# language: haskell
# cabal: "2.4"

# ghc:
#   - "8.6.4"

cache:
  directories:
  - $HOME/.stack
  - $HOME/.ghcjs
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/ghcjs/
  - $HOME/codeworld-account/.stack-work
  - $HOME/codeworld-api/.stack-work
  - $HOME/codeworld-auth/.stack-work
  - $HOME/codeworld-compiler/.stack-work
  - $HOME/codeworld-error-sanitizer/.stack-work
  - $HOME/codeworld-game-api/.stack-work
  - $HOME/codeworld-game-server/.stack-work
  - $HOME/codeworld-prediction/.stack-work
  - $HOME/codeworld-server/.stack-work

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
  - name: "root (no tests)"
    env: MODULE=. TEST=false
  - name: "account"
    env: MODULE=codeworld-account TEST=true
  - name: "api"
    env: MODULE=codeworld-api TEST=true
  - name: "auth"
    env: MODULE=codeworld-auth TEST=true
  - name: "compiler (no tests)"
    env: MODULE=codeworld-compiler TEST=false
  - name: "error-sanitizer"
    env: MODULE=codeworld-error-sanitizer TEST=true
  - name: "game-api"
    env: MODULE=codeworld-game-api TEST=true
  - name: "game-server"
    env: MODULE=codeworld-game-server TEST=true
  - name: "prediction"
    env: MODULE=codeworld-prediction TEST=true
  - name: "server"
    env: MODULE=codeworld-server TEST=true

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install -y cabal-install-2.4 ghc-8.6.2
- ls /opt/ghc/8.6.2/bin/
- sudo ln -s /opt/cabal/bin/cabal /usr/bin/cabal
- sudo ln -s /opt/ghc/8.6.2/bin/ghc /usr/bin/ghc
- sudo ln -s /opt/ghc/8.6.2/bin/ghc-pkg /usr/bin/ghc-pkg
- sudo ln -s /opt/ghc/8.6.2/bin/haddock /usr/bin/haddock
- sudo ln -s /opt/ghc/8.6.2/bin/ghci /usr/bin/ghci
- sudo ln -s /opt/ghc/8.6.2/bin/hpc /usr/bin/hpc
- sudo ln -s /opt/ghc/8.6.2/bin/runghc /usr/bin/runghc
- sudo ln -s /opt/ghc/8.6.2/bin/hsc2hs /usr/bin/hsc2hs
- echo $PATH
- cabal --version
- ghc --version

script:
  - stack install --resolver lts-14.11 happy-1.19.9 alex
  - git submodule update --init --recursive
  - cd ghcjs
  - git submodule update --init --recursive
  - ./utils/makePackages.sh
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
  - cabal install --enable-tests --enable-benchmarks -v --ghc-options="+RTS -c -RTS"
  - ghcjs --version
  - ghcjs-boot --version
  # - ghcjs-boot
  - cd ../$MODULE
  # - stack --resolver lts-14.11 build --fast
  # - if [ $TEST == "true" ]; then stack test --fast; fi
