jobs:
  - job: codeworld_account
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-account
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-account
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-account
          stack test
        displayName: Stack test
  - job: codeworld_api
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-api
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-api
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-api
          stack test
        displayName: Stack test
  - job: codeworld_auth
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-auth
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-auth
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-auth
          stack test
        displayName: Stack test
  - job: codeworld_base
    timeoutInMinutes: 1800
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-base
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-base
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-base
          stack test
        displayName: Stack test
  - job: codeworld_compiler
    timeoutInMinutes: 1800
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-compiler
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-compiler
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-compiler
          stack test
        displayName: Stack test
  - job: codeworld_error_sanitizer
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-error-sanitizer
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-error-sanitizer
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-error-sanitizer
          stack test
        displayName: Stack test
  - job: codeworld_game_api
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-api
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-api
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-api
          stack test
        displayName: Stack test
  - job: codeworld_game_server
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-server
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-server
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-game-server
          stack test
        displayName: Stack test
  - job: codeworld_prediction
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-prediction
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-prediction
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-prediction
          stack test
        displayName: Stack test
  - job: codeworld_server
    timeoutInMinutes: 1800
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-server
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-server
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-server
          stack test
        displayName: Stack test
  - job: funblocks_client
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=$HOME/.local/bin:$PATH
        displayName: Install Stack
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd funblocks-client
          stack setup
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-account
        displayName: Stack setup
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd codeworld-account
          stack build
        displayName: Stack build
      - script: |
          export PATH=$HOME/.local/bin:$PATH
          cd funblocks-client
          stack test
        displayName: Stack test
