resolver: lts-13.19

packages: 
  - codeworld-account
  - codeworld-api
  - codeworld-auth
  - codeworld-compiler
  - codeworld-error-sanitizer
  - codeworld-game-api
  - codeworld-game-server
  - codeworld-prediction
  - codeworld-server
  # compile ghcjs packages separately
  # - codeworld-base  
  # - funblocks-client

allow-newer: true
  
extra-deps:
  - blank-canvas-0.6.3
  - kansas-comet-0.4
  - jwt-0.9.0
  - containers-0.5.11.0
  - network-2.6.3.6
  - filesystem-trees-0.1.0.6
  - directory-1.2.7.1
  - hindent-5.2.7
  
