
packages:
  - .

extra-deps:
  - ghcjs-dom-0.8.0.0
  - ghcjs-dom-jsffi-0.8.0.0
  - github: ghcjs/ghcjs
    commit: 35a438302dafe7af9fb0e5956855f5578db0be10
    subdirs:
      - "lib/ghcjs-prim"

resolver: lts-8.22
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
  
