resolver: lts-13.19
        
packages:
  - .

allow-newer: false

extra-deps:
  - blank-canvas-0.6.3
  - kansas-comet-0.4
  - containers-0.5.11.0
  - network-2.6.3.6
  - ../codeworld-api
  - ../codeworld-game-api
