# resolver: lts-10.3

resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact


packages:
- .
- ../codeworld-error-sanitizer

docker:
  enable: true

# ghc-options:
#   "*": -j -threaded
  
