# resolver: lts-10.3

resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
# compiler-check: match-exact

# https://docs.haskellstack.org/en/stable/ghcjs/
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

extra-deps: [hindent-5.2.4.1, haskell-src-exts-1.20.1]

packages:
- .
- ../codeworld-error-sanitizer

docker:
  enable: true

# ghc-options:
#   "*": -j -threaded
  
