
packages:
  - .
  - ../codeworld-error-sanitizer

extra-deps:
  - haskell-src-exts-1.21.0


resolver: lts-13.26
# compiler: ghcjs-8.6.0.1_ghc-8.6.2
# compiler-check: newer-minor
# setup-info:
#   ghcjs:
#     source:
#       ghcjs-8.6.0.1_ghc-8.6.2:
#         url: /ghcjs

# docker:
#     enable: true
#     repo: "peterbecich/stack-build-ghcjs-8.6" # It will automatically add :lts-x.xx
#     # auto-pull: true
#     persist: true

# system-ghc: false
