# resolver: lts-10.3

resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

extra-deps: [hindent-5.2.4.1, haskell-src-exts-1.20.1]

packages:
- .
- ../codeworld-error-sanitizer

docker:
  enable: true

# ghc-options:
#   "*": -j -threaded
  
